### ISSUE TITLE
`SimRunner` error in dict obs for Ray Policies

### ISSUE THREAD

**Issue by dylan906** [dylan906/clockpunch#120]
Error in `SimRunner._computeSingleActionWrapper`.

Seems to be caused by dict observations being passed into `Policy.compute_single_action`.

```
Traceback (most recent call last):
  File "/home/dylanrpenn/clockpunch/tests/simulation/test_sim_runner.py", line 238, in <module>
    sim_runner = SimRunner(env=env, policy=policy, max_steps=horizon)
  File "/home/dylanrpenn/clockpunch/punchclock/simulation/sim_runner.py", line 115, in __init__
    self.reset()
  File "/home/dylanrpenn/clockpunch/punchclock/simulation/sim_runner.py", line 266, in reset
    action_init = self._computeSingleActionWrapper(self.obs_hist[0])
  File "/home/dylanrpenn/clockpunch/punchclock/simulation/sim_runner.py", line 131, in _computeSingleActionWrapper
    action, rnn_state, _ = self.policy.compute_single_action(
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 545, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 526, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/utils/threading.py", line 32, in wrapper
    raise e
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1159, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File "/home/dylanrpenn/anaconda3/envs/punch/lib/python3.10/site-packages/ray/rllib/models/modelv2.py", line 249, in __call__
    print(f"Line {inspect.currentframe().f_lineno}: {input_dict['obs'].shape=}")
AttributeError: 'collections.OrderedDict' object has no attribute 'shape'
```

**Comment by dylan906** [comment]
Needed to convert obs to tensor first. Now seems to work. Unsure of why SimRunner was working fine a couple of weeks ago without this fix.
