### ISSUE TITLE
test_mc.py fails

### ISSUE THREAD

**Issue by dylan906** [dylan906/clockpunch#24]
The test file for the MC runner is failing, look like an env config problem. Diagnose and fix. 
<details>
<summary>error message excerpt</summary>

```
Test runTrial...
register model
build policy from checkpoint
checkpoint path = tests/simulation/data/test_checkpoint/checkpoint_000200/policies/default_policy
...policy built
Generating new env seed.
RNG seed = 6934481978928862015
...
Traceback (most recent call last):
  File ".../clockpunch/tests/simulation/test_mc.py", line 32, in <module>
    mcr2.runTrial(
  File ".../clockpunch/punchclock/simulation/mc.py", line 343, in runTrial
    sim_runner = SimRunner(
  File ".../clockpunch/punchclock/simulation/sim_runner.py", line 103, in __init__
    self.reset()
  File ".../clockpunch/punchclock/simulation/sim_runner.py", line 246, in reset
    action_init = self._computeSingleActionWrapper(self.obs_hist[0])
  File ".../clockpunch/punchclock/simulation/sim_runner.py", line 116, in _computeSingleActionWrapper
    action = self.policy.compute_single_action(
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/policy/policy.py", line 545, in compute_single_action
    out = self.compute_actions_from_input_dict(
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/policy/torch_policy_v2.py", line 526, in compute_actions_from_input_dict
    return self._compute_action_helper(
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/utils/threading.py", line 24, in wrapper
    return func(self, *a, **k)
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/policy/torch_policy_v2.py", line 1159, in _compute_action_helper
    dist_inputs, state_out = self.model(input_dict, state_batches, seq_lens)
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/models/modelv2.py", line 247, in __call__
    restored["obs"] = restore_original_dimensions(
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/models/modelv2.py", line 411, in restore_original_dimensions
    return _unpack_obs(obs, original_space, tensorlib=tensorlib)
  File ".../anaconda3/envs/punch/lib/python3.9/site-packages/ray/rllib/models/modelv2.py", line 445, in _unpack_obs
    raise ValueError(
ValueError: Expected flattened obs shape of [..., 243], got torch.Size([1, 166])
```
</details>

relevant area in `test_mc.py`:
```python
print("\nTest runTrial...")
mcr2 = deepcopy(mcr)
mcr2.runTrial(
    trial_name=mcr2.trial_names[0],
    env_config=deepcopy(mcr2.env_config),
    policy_config_or_checkpoint=deepcopy(mcr2.policy_configs[0]),
)
```

**Comment by dylan906** [comment]
Problem is with loaded Ray policy. MC runs with custom policies.

Doesn't work:
```python
# Ray policy
mcr2.runTrial(
    trial_name=mcr2.trial_names[0],
    env_config=deepcopy(mcr2.env_config),
    policy_config_or_checkpoint=deepcopy(mcr2.policy_configs[0]),
)
```


Does work:
```python
# Ray policy
mcr2.runTrial(
    trial_name=mcr2.trial_names[1],
    env_config=deepcopy(mcr2.env_config),
    policy_config_or_checkpoint=deepcopy(mcr2.policy_configs[1]),
)
```
